/* Kabiyahe style reminder: Laguna Field Journal — warm paper canvas, forest-green editorial hierarchy, scenic image-led cards, asymmetric utility rails, and mobile-first thumb-reachable actions. */
import { useMemo, useState } from "react";
import { Link, Route, Switch, useLocation } from "wouter";
import {
  ArrowLeft, ArrowRight, Bell, Bookmark, CalendarDays, Check, ChevronDown,
  ChevronRight, Clock3, Compass, ExternalLink, Grid2X2, Heart, House,
  Landmark, List, Map, MapPin, Menu, Mountain, Navigation, Pencil, Plus,
  Search, Share2, SlidersHorizontal, Sparkles, Star, Ticket, Users,
  Utensils, WalletCards, X
} from "lucide-react";

const IMG = {
  hero: "/manus-storage/kabiyahe-hero-laguna_e334210c.jpg",
  lake: "/manus-storage/kabiyahe-calinaya-lake_96b9ff18.jpg",
  falls: "/manus-storage/kabiyahe-pagsanjan-falls_bd37de01.jpg",
  sunset: "/manus-storage/kabiyahe-bundles-sunset_99ff267e.jpg",
  emblem: "/manus-storage/kabiyahe-emblem_04426ca6.png",
};

const destinations = [
  { name: "Pagsanjan Falls", place: "Pagsanjan, Laguna", image: IMG.falls, type: "Nature", icon: Mountain, description: "Famous waterfall connected with the historic Pagsanjan Boat Ride.", rating: "4.7", reviews: "532" },
  { name: "Caliraya Lake", place: "Lumban, Laguna", image: IMG.lake, type: "Nature", icon: Mountain, description: "Scenic lake perfect for boating, camping, and relaxing.", rating: "4.6", reviews: "412" },
  { name: "Majayjay Church", place: "Majayjay, Laguna", image: IMG.sunset, type: "Culture", icon: Landmark, description: "Historic baroque church known as the Little Rome of the Philippines.", rating: "4.8", reviews: "298" },
  { name: "Los Baños Hot Springs", place: "Los Baños, Laguna", image: IMG.hero, type: "Relaxation", icon: Sparkles, description: "Warm mineral pools tucked into a lush mountain landscape.", rating: "4.7", reviews: "361" },
];
const bundles = [
  { name: "Laguna Weekend Escape", meta: "2 Days · 1 Night", image: IMG.lake, tags: ["Nature", "Relaxation"], clones: "1.2K" },
  { name: "Family Adventure", meta: "1 Day Trip", image: IMG.hero, tags: ["Family", "Adventure"], clones: "956" },
  { name: "Food + Culture Tour", meta: "1 Day Trip", image: IMG.sunset, tags: ["Food", "Culture"], clones: "842" },
  { name: "Nature & Relaxation", meta: "2 Days · 1 Night", image: IMG.falls, tags: ["Nature", "Relaxation"], clones: "1.1K" },
  { name: "Hidden Laguna Gems", meta: "1 Day Trip", image: IMG.sunset, tags: ["Hidden Gem", "Adventure"], clones: "673" },
];

function Header() {
  const [location] = useLocation();
  const nav = [{ label: "Explore", href: "/explore" }, { label: "Bundles", href: "/bundles" }, { label: "Plan a Trip", href: "/plan/new" }, { label: "My Trips", href: "/trips" }];
  return <header className="topbar">
    <Link href="/" className="brand"><img src={IMG.emblem} /><span>Kabiyahe<small>Tara na!</small></span></Link>
    <nav>{nav.map(n => <Link key={n.href} className={location.startsWith(n.href) ? "active" : ""} href={n.href}>{n.label}</Link>)}</nav>
    <div className="header-actions"><button className="icon-btn" aria-label="Notifications"><Bell size={20}/></button><div className="avatar">M</div><ChevronDown size={16}/><button className="mobile-menu"><Menu size={22}/></button></div>
  </header>
}
function BottomNav() { const [location] = useLocation(); return <div className="bottom-nav">{[{href:"/explore",label:"Explore",icon:Compass},{href:"/plan/new",label:"Plan",icon:Sparkles},{href:"/trips",label:"Trips",icon:Map},{href:"/saved",label:"Saved",icon:Heart}].map(n => {const I=n.icon; return <Link className={location.startsWith(n.href)?"active":""} href={n.href} key={n.href}><I size={19}/><span>{n.label}</span></Link>})}</div> }
function Tag({children, tone="sage"}:{children:React.ReactNode;tone?:string}) { return <span className={`tag ${tone}`}>{children}</span> }
function Button({children, variant="primary", href, onClick}:{children:React.ReactNode;variant?:string;href?:string;onClick?:()=>void}) { const cls=`btn ${variant}`; return href ? <Link href={href} className={cls}>{children}</Link> : <button onClick={onClick} className={cls}>{children}</button> }
function SectionTitle({eyebrow,title,action}:{eyebrow?:string;title:string;action?:React.ReactNode}) { return <div className="section-title">{eyebrow && <span className="eyebrow">{eyebrow}</span>}<h2>{title}</h2>{action && <div className="section-action">{action}</div>}</div> }
function DestinationCard({d, compact=false}:{d:any;compact?:boolean}) { const Icon=d.icon; return <article className={`destination-card ${compact?"compact":""}`}><div className="image-wrap"><img src={d.image}/><button className="save"><Heart size={17}/></button></div><div className="card-body"><div className="card-heading"><h3>{d.name}</h3><Bookmark size={16}/></div><p className="muted"><MapPin size={14}/>{d.place}</p><p className="desc">{d.description}</p><div className="card-footer"><Tag>{d.type}</Tag><span className="rating"><Star size={14} fill="currentColor"/> {d.rating} <small>({d.reviews})</small></span></div></div></article> }
function BundleCard({b}:{b:any}) { return <article className="bundle-card"><div className="image-wrap"><img src={b.image}/><Tag tone="ochre">Popular</Tag></div><div className="card-body"><h3>{b.name}</h3><p className="muted">{b.meta} <span>·</span> <Users size={14}/> 2–6</p><div className="card-footer"><div>{b.tags.map((t:string)=><Tag key={t}>{t}</Tag>)}</div><small><Users size={14}/> {b.clones} clones</small></div><Button variant="outline">View Trip <ArrowRight size={14}/></Button></div></article> }
function Home() { return <><Header/><main><section className="hero"><img className="hero-image" src={IMG.hero}/><div className="hero-overlay"/><div className="hero-copy"><p className="eyebrow">LAGUNA, PHILIPPINES</p><h1>Discover places.<br/>Create memories.</h1><div className="script">Tara na!</div><div className="accent-rule"/><p>Plan your Laguna adventure with<br/>AI-powered itineraries made for you.</p><div className="hero-actions"><Button href="/plan/new"><Sparkles size={17}/> Plan My Trip</Button><Button href="/explore" variant="secondary"><Compass size={17}/> Explore Laguna</Button></div></div></section><section className="container home-section"><SectionTitle title="Featured Destinations" action={<Link href="/explore" className="link-accent">⌖ View all destinations</Link>}/><div className="destination-grid">{destinations.map(d=><DestinationCard d={d} key={d.name}/>)}</div></section><section className="container explore-preview"><div><SectionTitle eyebrow="DISCOVER NEARBY" title="Explore Laguna"/><p>Discover amazing spots all over Laguna<br/>on our interactive map.</p><Button href="/explore"><Map size={17}/> Explore the Map</Button></div><div className="mini-map"><div className="map-water"/><div className="map-label one">Calamba City</div><div className="map-label two">Laguna<br/>de Bay</div>{["nature","food","culture","stay","gem"].map((x,i)=><span className={`pin ${x}`} style={{left:`${18+i*16}%`,top:`${28+(i%2)*27}%`}} key={x}>⌖</span>)}</div></section><section className="container home-section"><SectionTitle title="Popular Trip Bundles" action={<Link href="/bundles" className="link-accent">View all bundles <ChevronRight size={15}/></Link>}/><p className="section-subtitle">Hand-picked itineraries you can clone and customize.</p><div className="bundle-rail">{bundles.map(b=><BundleCard b={b} key={b.name}/>)}</div></section><section className="how-section"><div className="container"><SectionTitle title="How Kabiyahe Works"/><div className="steps">{[["01","Discover","Explore amazing places in Laguna you never knew existed.",Compass],["02","Plan","Let our AI build the perfect itinerary based on your preferences.",CalendarDays],["03","Go","Keep your itinerary and booking references with you, always.",WalletCards]].map(([n,t,c,I]:any)=><div className="step" key={n}><div className="step-icon"><I size={26}/></div><span>{n}</span><h3>{t}</h3><p>{c}</p></div>)}</div></div></section></main><BottomNav/></> }
function Explore() { const [view,setView]=useState("map"); const [query,setQuery]=useState(""); const filtered=useMemo(()=>destinations.filter(d=>d.name.toLowerCase().includes(query.toLowerCase())),[query]); return <><Header/><main className="explore-page"><aside className="filter-rail"><div className="rail-title"><h3>Categories</h3><ChevronDown size={15}/></div>{["All Categories","Nature & Parks","Attractions","Food & Restaurants","Hotels & Stays","Guides & Tours","Culture & Heritage","Hidden Gems"].map((x,i)=><button className={i===0?"selected":""} key={x}><Compass size={16}/>{x}</button>)}<div className="rail-title spaced"><h3>Tags</h3><ChevronDown size={15}/></div><div className="tag-cloud">{["Family Friendly","Adventure","Budget Friendly","Romantic","Relaxation","Waterfalls","Lakes & Rivers","Scenic Views"].map(x=><Tag key={x}>{x}</Tag>)}</div><div className="rail-title spaced"><h3>Price Range</h3><ChevronDown size={15}/></div><div className="price-line"><span/><i/><b/></div><div className="price-labels"><span>₱</span><span>₱₱</span><span>₱₱₱</span><span>₱₱₱₱</span></div></aside><section className="explore-content"><div className="page-heading"><div><h1>Explore Laguna</h1><p>Discover amazing places all over Laguna.</p></div><div className="search-row"><div className="searchbox"><Search size={18}/><input placeholder="Search destinations, places, or activities..." value={query} onChange={e=>setQuery(e.target.value)}/></div><Button variant="secondary"><SlidersHorizontal size={16}/> Filters</Button><div className="view-toggle">{[["map",Map],["list",List],["grid",Grid2X2]].map(([v,I]:any)=><button className={view===v?"active":""} onClick={()=>setView(v)} key={v}><I size={16}/><span>{v}</span></button>)}</div></div></div><div className={`explore-workspace ${view}`}><div className="result-list"><div className="result-count">{filtered.length*31+2} destinations found <span>Sort by: <b>Popular</b>⌄</span></div>{filtered.map(d=><DestinationCard d={d} compact key={d.name}/>)}<Button variant="soft">Load more destinations <ChevronDown size={16}/></Button></div><div className="map-field"><div className="map-copy">Laguna<br/><small>de Bay</small></div>{["nature","food","culture","stay","gem","nature","food","culture","stay"].map((x,i)=><span className={`pin ${x}`} style={{left:`${15+(i*11)%76}%`,top:`${16+(i*19)%70}%`}} key={i}>⌖</span>)}<div className="map-legend"><b>Categories</b>{[[Mountain,"Nature & Parks"],[Landmark,"Attractions"],[Utensils,"Food & Restaurants"],[WalletCards,"Hotels & Stays"]].map(([I,l]:any)=><span key={l}><I size={16}/>{l}</span>)}</div><Button variant="map-button"><Navigation size={15}/> Show near me</Button></div></div></section></main><BottomNav/></> }
const tripStops=[{time:"09:00 AM",name:"Pagsanjan Falls",place:"Pagsanjan, Laguna",image:IMG.falls,tags:["Nature","Adventure"],duration:"2 – 3 hrs",price:"₱₱ Moderate",booking:true},{time:"12:30 PM",name:"Local Lunch",place:"Pagsanjan, Laguna",image:IMG.hero,tags:["Food"],duration:"1 – 1.5 hrs",price:"₱₱ Budget-friendly",booking:true},{time:"03:00 PM",name:"Majayjay Church",place:"Majayjay, Laguna",image:IMG.sunset,tags:["Culture"],duration:"30 – 45 mins",price:"Free"},{time:"05:00 PM",name:"Los Baños Hot Springs",place:"Los Baños, Laguna",image:IMG.hero,tags:["Relaxation"],duration:"2 – 3 hrs",price:"₱₱₱ Moderate",booking:true},{time:"09:00 AM",name:"Caliraya Lake",place:"Lumban, Laguna",image:IMG.lake,tags:["Nature","Scenic Views"],duration:"2 – 3 hrs",price:"₱₱ Moderate",booking:true}];
function TripStop({s}:{s:any}) { return <div className="trip-stop"><div className="stop-time"><span className="timeline-dot"/>{s.time}</div><img src={s.image}/><div className="stop-main"><h3>{s.name}</h3><p className="muted"><MapPin size={14}/>{s.place}</p><div>{s.tags.map((t:string)=><Tag key={t}>{t}</Tag>)}</div></div><div className="stop-details"><p><Clock3 size={15}/>{s.duration}</p><p><span className="peso">₱</span>{s.price}</p><div className="stop-actions"><Button variant="outline"><Navigation size={14}/> Navigate</Button>{s.booking&&<Button variant="outline ochre"><Ticket size={14}/> Booking</Button>}</div></div><button className="more">•••</button></div> }
function TripPage() { return <><Header/><main className="trip-page container"><Link href="/trips" className="back-link"><ArrowLeft size={16}/> Back to My Trips</Link><div className="trip-top"><div><div className="trip-title-row"><h1>Laguna Weekend Escape <Pencil size={19}/></h1><div><Button variant="secondary"><Share2 size={16}/> Share</Button><Button variant="secondary"><Pencil size={16}/> Edit Trip</Button></div></div><p className="muted"><CalendarDays size={16}/> Jun 12 – Jun 13, 2025　•　2 Days, 1 Night　•　4 Travelers</p></div></div><div className="trip-layout"><section><div className="trip-tabs"><button className="active"><Map size={16}/> Itinerary</button><button><MapPin size={16}/> Map</button><button><WalletCards size={16}/> Wallet</button><button><Users size={16}/> Members</button></div><div className="day-block"><div className="day-header"><h2>☀️ DAY 1 <small>• June 12, 2025</small></h2><Button variant="secondary"><Plus size={16}/> Add Stop</Button></div>{tripStops.slice(0,4).map(s=><TripStop s={s} key={s.time+s.name}/>)}</div><div className="day-block"><div className="day-header"><h2>☀️ DAY 2 <small>• June 13, 2025</small></h2><Button variant="secondary"><Plus size={16}/> Add Stop</Button></div><TripStop s={tripStops[4]}/></div><Button variant="outline add-day"><Plus size={16}/> Add New Day</Button></section><aside className="trip-aside"><div className="side-card"><h2><WalletCards size={20}/> Trip Overview</h2><div className="overview-stats"><span><b>4</b>Stops</span><span><b>2</b>Days</span><span><b>~₱₱₱</b>Est. Budget</span><span><b>3</b>Bookings Saved</span></div><p>2 of 5 bookings saved</p><div className="progress"><span/></div></div><div className="side-card"><h2><Share2 size={20}/> Itinerary Actions</h2>{[[Share2,"Optimize Route","Reorder stops for the best travel flow"],[WalletCards,"Auto Estimate Costs","Recalculate total budget for your trip"],[Compass,"Duplicate Itinerary","Create a copy of this itinerary"],[X,"Clear Itinerary","Remove all stops and start over"]].map(([I,t,c]:any)=><button className={t.startsWith("Clear")?"danger action-row":"action-row"} key={t}><I size={21}/><span><b>{t}</b><small>{c}</small></span><ChevronRight size={16}/></button>)}</div><div className="side-card tip-card"><h2>ⓘ Helpful Tip</h2><p>Drag and drop stops to reorder your itinerary.</p></div><div className="side-card note-card"><h2>▤ Travel Note <Pencil size={16}/></h2><p>Bring swimwear for hot springs and extra clothes for the boat ride.</p></div></aside></div></main><BottomNav/></> }
function Bundles(){return <><Header/><main className="container listing-page"><div className="listing-heading"><div><p className="eyebrow">CURATED FOR YOU</p><h1>Ready-made trips.</h1><p>Find a trip that already fits your vibe.</p></div><Button href="/plan/new"><Sparkles size={17}/> Plan your own</Button></div><div className="filter-pills">{["All","Family","Adventure","Romantic","Budget","Nature"].map((x,i)=><button className={i===0?"active":""} key={x}>{x}</button>)}</div><div className="bundle-grid">{bundles.concat(bundles.slice(0,2)).map((b,i)=><BundleCard b={b} key={i}/>)}</div></main><BottomNav/></>}
function Plan(){ const [selected,setSelected]=useState(["Nature","Food","Relaxation","Hidden Gems"]); return <><Header/><main className="container plan-page"><div className="plan-heading"><div className="plan-illustration"><img src={IMG.emblem}/></div><div><h1>Plan Your Adventure <Sparkles size={22}/></h1><p>Tell us about your trip and let Kabiyahe create the perfect itinerary<br/>just for you.</p></div></div><div className="plan-layout"><section className="form-card"><div className="stepper"><span className="current">1</span><b>Trip Details<small>Tell us the basics</small></b><i/><span>2</span><b>Preferences<small>Your interests & style</small></b><i/><span>3</span><b>Review<small>Generate itinerary</small></b></div><div className="form-grid"><label><span><CalendarDays/> Travel Dates</span><small>When are you traveling?</small><div className="date-row"><div>Check-in / Start date<br/><b>Jun 12, 2025</b></div><div>Check-out / End date<br/><b>Jun 13, 2025</b></div></div></label><label><span><Users/> Group Size</span><small>How many are in your group?</small><div className="counter"><button>−</button><b>4</b><button>+</button></div><small>♙ Travelers</small></label><label><span><WalletCards/> Budget Range</span><small>What's your budget like?</small><div className="budget-row">{["₱","₱₱","₱₱₱","₱₱₱₱"].map((x,i)=><button className={i===1?"selected":""} key={x}><b>{x}</b><small>{["Budget","Moderate","Comfort","Luxury"][i]}</small></button>)}</div></label></div><div className="interest-section"><h3>♡　What are you interested in?</h3><p>Choose the things you and your group love.</p><div className="interest-grid">{["Nature","Adventure","Food","Culture","Relaxation","Family Friendly","Romance","Hidden Gems"].map(x=><button className={selected.includes(x)?"selected":""} onClick={()=>setSelected(s=>s.includes(x)?s.filter(v=>v!==x):[...s,x])} key={x}><Compass size={18}/>{x}{selected.includes(x)&&<Check size={16}/>}</button>)}</div><h3 className="other">▤　Any other preferences? <small>(Optional)</small></h3><p>Add notes or special requests for your trip.</p><textarea placeholder="Example: We prefer chill places, not too crowded. We want to try local food!"/><div className="form-actions"><Button variant="secondary"><ArrowLeft size={16}/> Back</Button><Button>Next: Review & Generate <ArrowRight size={16}/></Button></div></div></section><aside className="summary-card"><h2>Your Trip Summary</h2><img src={IMG.lake}/><h3>Laguna Adventure <Pencil size={15}/></h3><p><CalendarDays size={15}/> Jun 12 – Jun 13, 2025 <span>2 Days, 1 Night</span></p><p><Users size={15}/> 4 Travelers</p><p><WalletCards size={15}/> Budget: ₱₱ Moderate</p><p><Heart size={15}/> Interests</p><div>{selected.map(x=><Tag key={x}>{x}</Tag>)}</div><div className="info-box">ⓘ Our AI will create an itinerary based on verified destinations in Laguna.</div></aside></div></main><BottomNav/></>}
function Trips(){return <><Header/><main className="container trips-page"><div className="listing-heading"><div><h1>My Trips <Sparkles size={22}/></h1><p>All your adventures, plans, and booking references in one place.</p></div><Button href="/plan/new"><Plus size={17}/> New Trip</Button></div><div className="filter-pills trip-filters">{["All Trips","Upcoming","Active","Completed","Archived"].map((x,i)=><button className={i===0?"active":""} key={x}>{x}</button>)}</div>{[{name:"Laguna Weekend Escape",image:IMG.lake,status:"Starts in 5 days",meta:"Jun 12 – Jun 13, 2025　•　2 Days, 1 Night　•　4 Travelers",tags:["Nature","Relaxation","Family Friendly"],saved:"2 of 5 bookings saved"},{name:"Laguna Adventure",image:IMG.falls,status:"In Progress",meta:"May 24 – May 25, 2025　•　2 Days, 1 Night　•　3 Travelers",tags:["Adventure","Nature"],saved:"4 of 6 bookings saved"},{name:"Caliraya Relaxation Trip",image:IMG.sunset,status:"In Progress",meta:"Apr 5 – Apr 6, 2025　•　2 Days, 1 Night　•　2 Travelers",tags:["Relaxation","Scenic"],saved:"3 of 4 bookings saved"}].map((t,i)=><article className="trip-card" key={t.name}><img src={t.image}/><div><Tag tone={i===0?"cream":"sage"}>{t.status}</Tag><h2>{t.name} <Pencil size={16}/></h2><p className="muted"><MapPin size={14}/>{t.meta}</p><div>{t.tags.map(x=><Tag key={x}>{x}</Tag>)}</div><p>Budget: <b>₱₱ Moderate</b></p><small>{t.saved}</small><div className="progress"><span style={{width:`${42+i*22}%`}}/></div><div className="trip-card-actions"><Button href={i===0?"/trips/laguna-weekend":"/trips/laguna-weekend"} variant="outline"><Map size={14}/> View Itinerary</Button><Button variant="outline"><WalletCards size={14}/> Bookings</Button><Button variant="primary">{i===0?"Continue Planning":"Open Trip"} <ArrowRight size={15}/></Button></div></div></article>)}</main><BottomNav/></>}
function NotFound(){return <><Header/><main className="empty-page"><img src={IMG.emblem}/><h1>That trail is still being mapped.</h1><p>Try one of the routes below.</p><Button href="/">Back home</Button></main><BottomNav/></>}
export default function App(){return <Switch><Route path="/" component={Home}/><Route path="/explore" component={Explore}/><Route path="/bundles" component={Bundles}/><Route path="/plan/new" component={Plan}/><Route path="/trips/:id" component={TripPage}/><Route path="/trips" component={Trips}/><Route component={NotFound}/></Switch>}
